### ISSUE TITLE
Ossec server and agent on the same machine

### ISSUE THREAD

**Issue by Vincent--** [wazuh/ossec-puppet#46]
Hey,

I'm trying to install the ossec agent on the ossec server (as this module doesnt seem to provide an hybrid mode) but I get this error message:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Class[Ossec::Repo] is already declared in file /var/lib/rg_data/puppet/environments/production/modules/ossec/manifests/client.pp:39; cannot redeclare at /var/lib/rg_data/puppet/environments/production/modules/ossec/manifests/server.pp:48 on node siem
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Is there a workaround against that?

Regards,
Vincent

**Comment by jlruizmlg** [comment]
Hi @Vincent-- this module install Ossec through packages, and we don't have packages to install Ossec Server in hybrid mode.
Also the agent package cannot be installed in one server with a manager package already installed.

You want to install the manager in hybrid mode because you want to monitor this manager with other Ossec Manager? or why you like to install one agent in one Ossec Manager?

The Ossec Manager has its own agent.

**Comment by Vincent--** [comment]
Hi @jlruizmlg,

Thanks for this update. I'd like to monitor all the boxes available  in my setup, including the ossec server. I didn't know that Ossec Manager has its own agent, I thought it can only do that in hybrid mode. I'll have a look then, that should meet my expectations :-)

Thank you again
