### ISSUE TITLE
Consistency of client configuration

### ISSUE THREAD

**Issue by kdole** [wazuh/ossec-puppet#61]
As I understand it there are three main configuration files in play for this module: `ossec.conf` on the server, `ossec.conf` on the client, and `shared/agent.conf` which the server pushes to the client.

The way this module handles them seems inconsistent. In the case of `ossec_scanpaths`, a default list is set on the server but not the client, while `shared/agent.conf` has a default, but it is different from the server default and is hard-coded.

Is there a reason behind this? I don't know much about OSSEC, but it seems like a default installation should at least set reasonable and consistent defaults on both the server and client. I'm willing to work on a PR, but wanted to check in first.

**Comment by jlruizmlg** [comment]
Hi @kdole We didn't include default list in the agent because one agent can be installed in Linux/Windows and soon in macOS, instead the manager, only available to install in Linux.

But anyway every idea is welcome!, thanks for your hard work this weekend with this module, i will take a look soon and merge!
