### ISSUE TITLE
Unable to manage agent with Puppet

### ISSUE THREAD

**Issue by hussainaphroj** [wazuh/ossec-puppet#76]
Hi,

I am struggling to manage the ossec agents through given puppet module. I have configure ossec-server , agent  and can see the client.keys is present but server is not showing any active agent. 

ossec-server
------
rpm -qa | grep ossec              
ossec-hids-2.8.3-3.el6.x86_64

udp        0      0 0.0.0.0:1514                0.0.0.0:* 

./list_agents -c                  
** No agent available

Ossec-agent
-------
rpm -qa | grep ossec                 
ossec-hids-agent-2.8.3-4.el6.x86_64

cat /var/ossec/etc/client.keys
<agent_id> <hostname> <ip> <cipher>

netstat -anlp | grep ossec
udp        0      0 <ossec_agentip>:44534         <ossec_sever_ip>:1514         ESTABLISHED

Any help will be appreciated

Thanks,
Hussain

**Comment by philsynek** [comment]
What I learned is, that the agent configuration for the server ip via

`class { "wazuh::client":
  ossec_server_ip => "W.X.Y.Z"
}`

seems not to be enough. Unfortunately the agent does not auth at the server... I saw "not allowed" warnings in the ossec.log: `2017/05/31 13:14:12 ossec-remoted(1213): WARN: Message from 'A.B.C.D' not allowed.` I had to manually auth the agent with `/var/ossec/bin/agent-auth -m W.X.Y.Z`

After that it worked and I saw the agent connected. Maybe this helps you.

Unfortunately now I have the problem how to rollout the agents with puppet? I could run the auth command on the shell, but if an agent is already registered I get another agententry with an appending "2" for the hostname on my server and I can't seem to determine from the agent side if the agent is already registered to the server.

Any ideas?
Phil

**Comment by jlruizmlg** [comment]
Hi @hussainaphroj 

You run puppet in the manager after the agent installation?

When you ran the ossec client class, the client.keys is autogenerated in the client side, then we use exported resources to store this client.keys in the Puppet database, but at this point the manager doesn't know about the new client.keys.

In order to finish the installation, you need to run Puppet again in the manager, in this case, puppet should take the agent or agents keys information from the database and apply in the manager, and at this moment your client should be connected and running.

**Comment by hussainaphroj** [comment]
Thank you Jose, It worked.
